app:
  domain: ""
  port: ""
  uuid: "e88e0d74-af97-413f-b72a-d7c1078f60b4"
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: ""
  argo-token: ""
  remarks-prefix: ""
